# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.FloatField()),
                ('timestamp', models.FloatField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Position')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Telemetry')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Position')),
            ],
        ),
        migrations.AddField(
            model_name='obstacle',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Position'),
        ),
    ]
