# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, choices=[('auto', 'auto'), ('guided', 'guided')], default='auto', max_length=10)),
                ('armed', models.BooleanField(default=False)),
                ('gain_p', models.FloatField(blank=True, default=1)),
                ('gain_speed', models.FloatField(blank=True, default=1)),
                ('waypoint_index', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='heading',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='timestamp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclestate',
            name='settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.VehicleSettings'),
        ),
    ]
