# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20171107_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frommatlab', models.BooleanField(default=True)),
            ],
        ),
    ]
