# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='boatid',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
